scripts: Various Updates
Remove unused helper functions.

Use uv instead of rye for Python

Simplify Rust tool installation

diff --git a/home/.chezmoiscripts/run_before_00-bootstrap.sh.tmpl b/home/.chezmoiscripts/run_before_00-bootstrap.sh.tmpl
--- a/home/.chezmoiscripts/run_before_00-bootstrap.sh.tmpl
+++ b/home/.chezmoiscripts/run_before_00-bootstrap.sh.tmpl
@@ -3,72 +3,72 @@
 # vim:ft=bash
 set -eufo pipefail
 
-declare -r red=$(tput setaf 1)
-declare -r red_bg=$(tput setab 1)
-declare -r green=$(tput setaf 2)
-declare -r white=$(tput setaf 7)
-declare -r normal=$(tput sgr0) # Reset / No Color
-declare -r bold=$(tput bold)
+declare -r red="$(tput setaf 1)"
+declare -r red_bg="$(tput setab 1)"
+declare -r green="$(tput setaf 2)"
+declare -r white="$(tput setaf 7)"
+declare -r normal="$(tput sgr0)" # Reset / No Color
+declare -r bold="$(tput bold)"
 
 start() {
-    printf "${green}▶ ${normal}${bold}$1${normal}\n"
+  printf "${green}▶ ${normal}${bold}$1${normal}\n"
 }
 
 command_exists() {
-    type "${1}" >/dev/null 2>&1
+  type "${1}" > /dev/null 2>&1
 }
 
 has_brew() {
-    if declare -p HOMEBREW_PREFIX &>/dev/null ; then
-        BREW="$HOMEBREW_PREFIX/bin/brew"
+  if declare -p HOMEBREW_PREFIX &> /dev/null; then
+    BREW="$HOMEBREW_PREFIX/bin/brew"
+  else
+    if [[ -x /opt/homebrew/bin/brew ]]; then
+      BREW=/opt/homebrew/bin/brew
+    elif [[ -x /usr/local/bin/brew ]]; then
+      BREW=/usr/local/bin/brew
+    elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
+      BREW=/home/linuxbrew/.linuxbrew/bin/brew
     else
-        if [[ -x /opt/homebrew/bin/brew ]]; then
-            BREW=/opt/homebrew/bin/brew
-        elif [[ -x /usr/local/bin/brew ]]; then
-            BREW=/usr/local/bin/brew
-        elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
-            BREW=/home/linuxbrew/.linuxbrew/bin/brew
-        else
-            return 1
-        fi
-
-        eval "$("$BREW" shellenv)"
+      return 1
     fi
 
-    export BREW=$BREW
+    eval "$("$BREW" shellenv)"
+  fi
 
-    return 0
+  export BREW=$BREW
+
+  return 0
 }
 
 install_homebrew() {
-    if ! command_exists brew; then
-        start "Installing Homebrew.."
+  if ! command_exists brew; then
+    start "Installing Homebrew.."
 
-        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-    fi
+    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  fi
 }
 
 install_package() {
-    package="$1"
+  package="$1"
 
-    if ! command_exists "$package"; then
-        start "Installing $package from Homebrew."
-        $BREW install -q "$package" >/dev/null 2>&1
-    fi
+  if ! command_exists "$package"; then
+    start "Installing $package from Homebrew."
+    "$BREW" install -q "$package" > /dev/null 2>&1
+  fi
 }
 
 install_homebrew
 
 if has_brew; then
-    install_package age
-    install_package fish
+  install_package age
+  install_package fish
 
-    if [[ $CHEZMOI_OS == darwin ]]; then
-        # Sonoma+ allows a sudo_local file in /etc/pam.d/
-        sudo cp -f "${HOME}/.config/system/etc/pam.d/sudo_local" /etc/pam.d/sudo_local
+  if [[ $CHEZMOI_OS == darwin ]]; then
+    # Sonoma+ allows a sudo_local file in /etc/pam.d/
+    sudo cp -f "${HOME}/.config/system/etc/pam.d/sudo_local" /etc/pam.d/sudo_local
 
-        install_package mas
-    fi
+    install_package mas
+  fi
 else
-    printf "${red}✖ ${red_bg}${bold}${white} ERROR ${normal} Can't find Homebrew in the PATH.${normal}\n"
+  printf "${red}✖ ${red_bg}${bold}${white} ERROR ${normal} Can't find Homebrew in the PATH.${normal}\n"
 fi
